// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsexports = {
  aws_appsync_graphqlEndpoint: '',
  aws_appsync_region: '',
  aws_appsync_authenticationType: '',
  aws_appsync_apiKey: '',
  Auth: {
    region: '',
    userPoolId: '',
    userPoolWebClientId: '',
  },
};

export default awsexports;
