name: Format with Prettier

on:
  pull_request:
    branches: [develop]
    paths-ignore:
      - '.github/**'
      - '.vscode/**'

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.2
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}
          # This is important to fetch the changes to the previous commit
          fetch-depth: 0

      - name: Prettify code
        uses: creyD/prettier_action@v4.2
        with:
          same_commit: True
          prettier_options: --write **/*.{ts,js,md,html,css,less,scss,json,xml} --ignore-unknown
          only_changed: True
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
